import { Enemy, Item, Location, Merchant, NPC, Quest, Recipe } from './game-types';

const EN = 'en';
const RU = 'ru';

export const EXPANSION_RECIPES: Record<string, Recipe> = {
  recipe_sunfire_tonic: {
    id: 'recipe_sunfire_tonic',
    name: { en: 'Sunfire Tonic', ru: 'Тоник солнечного жара' },
    resultItemId: 'potion_sunfire',
    resultQuantity: 1,
    requiredStation: 'alchemy_table',
    ingredients: [
      { itemId: 'sun_salt', quantity: 2 },
      { itemId: 'moon_herb', quantity: 1 },
    ],
  },
  recipe_veilstep_dose: {
    id: 'recipe_veilstep_dose',
    name: { en: 'Veilstep Dose', ru: 'Доза призрачного шага' },
    resultItemId: 'potion_veilstep',
    resultQuantity: 1,
    requiredStation: 'alchemy_table',
    ingredients: [
      { itemId: 'veil_thread', quantity: 2 },
      { itemId: 'glass_bloom', quantity: 1 },
    ],
  },
  recipe_guard_tonic: {
    id: 'recipe_guard_tonic',
    name: { en: 'Guard Tonic', ru: 'Тоник бастиона' },
    resultItemId: 'potion_guard_tonic',
    resultQuantity: 1,
    requiredStation: 'alchemy_table',
    ingredients: [
      { itemId: 'sun_salt', quantity: 1 },
      { itemId: 'dawn_opal', quantity: 1 },
    ],
  },
  recipe_sun_lance: {
    id: 'recipe_sun_lance',
    name: { en: 'Sun Lance', ru: 'Солнечное копьё' },
    resultItemId: 'weapon_sun_lance',
    resultQuantity: 1,
    requiredStation: 'forge',
    ingredients: [
      { itemId: 'brass_core', quantity: 2 },
      { itemId: 'dawn_opal', quantity: 2 },
      { itemId: 'iron_ore', quantity: 3 },
    ],
  },
  recipe_glass_mail: {
    id: 'recipe_glass_mail',
    name: { en: 'Glass Mail', ru: 'Стеклянная кольчуга' },
    resultItemId: 'armor_glass_mail',
    resultQuantity: 1,
    requiredStation: 'forge',
    ingredients: [
      { itemId: 'glass_bloom', quantity: 4 },
      { itemId: 'silver_ore', quantity: 2 },
    ],
  },
  recipe_dawn_robe: {
    id: 'recipe_dawn_robe',
    name: { en: 'Dawn Robe', ru: 'Роба рассвета' },
    resultItemId: 'armor_dawn_robe',
    resultQuantity: 1,
    requiredStation: 'runic_workbench',
    ingredients: [
      { itemId: 'dawn_opal', quantity: 2 },
      { itemId: 'silk_fiber', quantity: 3 },
      { itemId: 'phoenix_ash', quantity: 1 },
    ],
  },
};

export const EXPANSION_ITEMS: Record<string, Item> = {
  sun_salt: { id: 'sun_salt', name: { [EN]: 'Sun Salt', [RU]: 'Солнечная соль' }, description: { [EN]: 'Salt crystals warmed by constant light.', [RU]: 'Кристаллы соли, прогретые постоянным светом.' }, type: 'material', slotCategory: 'material', rarity: 'common', value: 20, weight: 0.4 },
  glass_bloom: { id: 'glass_bloom', name: { [EN]: 'Glass Bloom', [RU]: 'Стеклянный цветок' }, description: { [EN]: 'Brittle mineral petals from shattered dunes.', [RU]: 'Хрупкие минеральные лепестки из расколотых дюн.' }, type: 'material', slotCategory: 'material', rarity: 'uncommon', value: 30, weight: 0.3 },
  dawn_opal: { id: 'dawn_opal', name: { [EN]: 'Dawn Opal', [RU]: 'Рассветный опал' }, description: { [EN]: 'A prismatic core used in precision craft.', [RU]: 'Призматическое ядро для точного ремесла.' }, type: 'material', slotCategory: 'material', rarity: 'rare', value: 56, weight: 0.2 },
  brass_core: { id: 'brass_core', name: { [EN]: 'Brass Core', [RU]: 'Латунное ядро' }, description: { [EN]: 'Engine heart from ancient war machines.', [RU]: 'Сердечник из древних боевых машин.' }, type: 'material', slotCategory: 'material', rarity: 'rare', value: 66, weight: 0.9 },
  relic_ink: { id: 'relic_ink', name: { [EN]: 'Relic Ink', [RU]: 'Реликтовые чернила' }, description: { [EN]: 'Thick pigment used to mark warding runes.', [RU]: 'Густой пигмент для маркировки охранных рун.' }, type: 'material', slotCategory: 'material', rarity: 'uncommon', value: 34, weight: 0.2 },
  veil_thread: { id: 'veil_thread', name: { [EN]: 'Veil Thread', [RU]: 'Нить завесы' }, description: { [EN]: 'Thread that bends light around armor seams.', [RU]: 'Нить, искажающая свет на швах брони.' }, type: 'material', slotCategory: 'material', rarity: 'uncommon', value: 33, weight: 0.1 },
  dune_chitin: { id: 'dune_chitin', name: { [EN]: 'Dune Chitin', [RU]: 'Дюнный хитин' }, description: { [EN]: 'Layered shell from desert predators.', [RU]: 'Слоистый панцирь пустынных хищников.' }, type: 'material', slotCategory: 'material', rarity: 'common', value: 24, weight: 0.6 },
  phoenix_ash: { id: 'phoenix_ash', name: { [EN]: 'Phoenix Ash', [RU]: 'Пепел феникса' }, description: { [EN]: 'Hot ash still carrying residual arcane charge.', [RU]: 'Горячий пепел с остаточным тайным зарядом.' }, type: 'material', slotCategory: 'material', rarity: 'rare', value: 72, weight: 0.3 },
  weapon_sun_lance: { id: 'weapon_sun_lance', name: { [EN]: 'Sun Lance', [RU]: 'Солнечное копьё' }, description: { [EN]: 'Balanced spear that pierces armor seams.', [RU]: 'Сбалансированное копьё, пробивающее уязвимые швы брони.' }, type: 'weapon', slotCategory: 'gear', rarity: 'epic', value: 600, weight: 4.2, stats: { damage: [12, 19], damageType: 'physical', critChanceBonus: 0.07 } },
  weapon_glass_dagger: { id: 'weapon_glass_dagger', name: { [EN]: 'Glass Dagger', [RU]: 'Стеклянный кинжал' }, description: { [EN]: 'Light blade built for precise strikes.', [RU]: 'Лёгкий клинок для точных ударов.' }, type: 'weapon', slotCategory: 'gear', rarity: 'rare', value: 305, weight: 1.4, stats: { damage: [8, 14], damageType: 'physical', critChanceBonus: 0.1 } },
  weapon_brass_halberd: { id: 'weapon_brass_halberd', name: { [EN]: 'Brass Halberd', [RU]: 'Латунная алебарда' }, description: { [EN]: 'Heavy polearm for controlled frontline pressure.', [RU]: 'Тяжёлое древковое оружие для давления на передней линии.' }, type: 'weapon', slotCategory: 'gear', rarity: 'epic', value: 650, weight: 6.9, stats: { damage: [13, 21], damageType: 'physical', counterChanceBonus: 0.07 } },
  weapon_veil_bow: { id: 'weapon_veil_bow', name: { [EN]: 'Veil Bow', [RU]: 'Лук завесы' }, description: { [EN]: 'Runic bow optimized for opportunistic hits.', [RU]: 'Рунический лук для атак по уязвимым целям.' }, type: 'weapon', slotCategory: 'gear', rarity: 'epic', value: 620, weight: 2.8, stats: { damage: [11, 18], damageType: 'physical', critChanceBonus: 0.08 } },
  armor_dune_cloak: { id: 'armor_dune_cloak', name: { [EN]: 'Dune Cloak', [RU]: 'Дюнный плащ' }, description: { [EN]: 'Flexible cloak reducing movement noise.', [RU]: 'Гибкий плащ, снижающий заметность движений.' }, type: 'armor', slotCategory: 'gear', rarity: 'rare', value: 300, weight: 3.8, stats: { defense: 6, critChanceBonus: 0.03 } },
  armor_glass_mail: { id: 'armor_glass_mail', name: { [EN]: 'Glass Mail', [RU]: 'Стеклянная кольчуга' }, description: { [EN]: 'Layered mail balancing speed and impact resistance.', [RU]: 'Слоистая кольчуга с балансом скорости и защиты.' }, type: 'armor', slotCategory: 'gear', rarity: 'epic', value: 610, weight: 8.1, stats: { defense: 11 } },
  armor_catacomb_plate: { id: 'armor_catacomb_plate', name: { [EN]: 'Catacomb Plate', [RU]: 'Катакомбный панцирь' }, description: { [EN]: 'Relic-marked plate tuned for prolonged engagements.', [RU]: 'Панцирь с реликтовыми метками для затяжных боёв.' }, type: 'armor', slotCategory: 'gear', rarity: 'epic', value: 670, weight: 11.2, stats: { defense: 12, counterChanceBonus: 0.05 } },
  armor_dawn_robe: { id: 'armor_dawn_robe', name: { [EN]: 'Dawn Robe', [RU]: 'Роба рассвета' }, description: { [EN]: 'Runic robe focused on sustained combat flow.', [RU]: 'Руническая роба для контроля темпа затяжного боя.' }, type: 'armor', slotCategory: 'gear', rarity: 'rare', value: 390, weight: 3.2, stats: { defense: 7, critChanceBonus: 0.04 } },
  potion_sunfire: { id: 'potion_sunfire', name: { [EN]: 'Sunfire Tonic', [RU]: 'Тоник солнечного жара' }, description: { [EN]: 'Restores 28 HP and steadies your breath.', [RU]: 'Восстанавливает 28 HP и стабилизирует дыхание.' }, type: 'consumable', slotCategory: 'potion', rarity: 'rare', value: 94, weight: 0.4, stats: { heal: 28 } },
  potion_veilstep: { id: 'potion_veilstep', name: { [EN]: 'Veilstep Dose', [RU]: 'Доза призрачного шага' }, description: { [EN]: 'Restores 32 energy for sustained skirmishes.', [RU]: 'Восстанавливает 32 энергии для затяжных стычек.' }, type: 'consumable', slotCategory: 'potion', rarity: 'rare', value: 96, weight: 0.4, stats: { energyRestore: 32 } },
  potion_guard_tonic: { id: 'potion_guard_tonic', name: { [EN]: 'Guard Tonic', [RU]: 'Тоник бастиона' }, description: { [EN]: 'Restores 22 HP and 18 energy.', [RU]: 'Восстанавливает 22 HP и 18 энергии.' }, type: 'consumable', slotCategory: 'potion', rarity: 'rare', value: 98, weight: 0.5, stats: { heal: 22, energyRestore: 18 } },
  bomb_glass_shard: { id: 'bomb_glass_shard', name: { [EN]: 'Glass Shard Bomb', [RU]: 'Бомба стеклянных осколков' }, description: { [EN]: 'Explodes into piercing shards.', [RU]: 'Взрывается градом пробивающих осколков.' }, type: 'consumable', slotCategory: 'potion', rarity: 'rare', value: 102, weight: 0.5, stats: { throwDamage: [14, 22], damageType: 'physical' } },
  bomb_dusk_smoke: { id: 'bomb_dusk_smoke', name: { [EN]: 'Dusk Smoke Bomb', [RU]: 'Сумеречная дымовая бомба' }, description: { [EN]: 'Smoke charge with toxic residue.', [RU]: 'Дымовой заряд с токсичным остатком.' }, type: 'consumable', slotCategory: 'potion', rarity: 'epic', value: 126, weight: 0.6, stats: { throwDamage: [11, 17], damageType: 'poison', statusOnHit: { type: 'poisoned', chance: 0.75, duration: 3, potency: 5 } } },
  scroll_sun_lance: { id: 'scroll_sun_lance', name: { [EN]: 'Recipe: Sun Lance', [RU]: 'Рецепт: Солнечное копьё' }, description: { [EN]: 'Teaches Sun Lance forging.', [RU]: 'Обучает ковке Солнечного копья.' }, type: 'recipe', rarity: 'rare', value: 220, weight: 0.1, teachesRecipeId: 'recipe_sun_lance' },
  scroll_veilstep: { id: 'scroll_veilstep', name: { [EN]: 'Recipe: Veilstep Dose', [RU]: 'Рецепт: Доза призрачного шага' }, description: { [EN]: 'Teaches Veilstep potion crafting.', [RU]: 'Обучает созданию зелья призрачного шага.' }, type: 'recipe', rarity: 'rare', value: 190, weight: 0.1, teachesRecipeId: 'recipe_veilstep_dose' },
};

export const EXPANSION_ENEMIES: Record<string, Enemy> = {
  glass_stalker: { id: 'glass_stalker', name: { [EN]: 'Glass Stalker', [RU]: 'Стеклянный охотник' }, role: 'berserker', level: 8, hp: 94, maxHp: 94, maxEnergy: 90, damage: [11, 17], damageType: 'physical', xpReward: 138, goldReward: [36, 74], dropTable: [{ itemId: 'glass_bloom', chance: 0.8, min: 1, max: 2 }, { itemId: 'veil_thread', chance: 0.5, min: 1, max: 1 }] },
  dune_reaver: { id: 'dune_reaver', name: { [EN]: 'Dune Reaver', [RU]: 'Дюнный мародёр' }, role: 'berserker', level: 8, hp: 102, maxHp: 102, maxEnergy: 84, damage: [12, 18], damageType: 'physical', xpReward: 142, goldReward: [42, 80], dropTable: [{ itemId: 'dune_chitin', chance: 0.7, min: 1, max: 2 }] },
  sun_automaton: { id: 'sun_automaton', name: { [EN]: 'Sun Automaton', [RU]: 'Солнечный автоматон' }, role: 'tank', level: 9, hp: 132, maxHp: 132, maxEnergy: 72, damage: [12, 19], damageType: 'fire', resistances: { fire: 0.18, poison: 0.12 }, xpReward: 170, goldReward: [54, 96], dropTable: [{ itemId: 'brass_core', chance: 0.75, min: 1, max: 2 }, { itemId: 'sun_salt', chance: 0.55, min: 1, max: 2 }] },
  oathbreaker_duelist: { id: 'oathbreaker_duelist', name: { [EN]: 'Oathbreaker Duelist', [RU]: 'Клятвопреступник-дуэлянт' }, role: 'berserker', level: 9, hp: 110, maxHp: 110, maxEnergy: 110, damage: [13, 20], damageType: 'physical', adaptiveProfile: { punishBlocking: true }, xpReward: 176, goldReward: [58, 102], dropTable: [{ itemId: 'relic_ink', chance: 0.7, min: 1, max: 2 }, { itemId: 'dawn_opal', chance: 0.35, min: 1, max: 1 }] },
  crypt_wailer: { id: 'crypt_wailer', name: { [EN]: 'Crypt Wailer', [RU]: 'Катакомбный вопль' }, role: 'alchemist', level: 9, hp: 98, maxHp: 98, maxEnergy: 125, damage: [11, 18], damageType: 'arcane', statusInflict: { type: 'stunned', chance: 0.24, duration: 1, potency: 1 }, xpReward: 168, goldReward: [48, 90], dropTable: [{ itemId: 'veil_thread', chance: 0.65, min: 1, max: 2 }, { itemId: 'phoenix_ash', chance: 0.22, min: 1, max: 1 }] },
  carrion_drake: { id: 'carrion_drake', name: { [EN]: 'Carrion Drake', [RU]: 'Падальный дрейк' }, role: 'tank', level: 10, hp: 154, maxHp: 154, maxEnergy: 98, damage: [14, 22], damageType: 'poison', statusInflict: { type: 'poisoned', chance: 0.5, duration: 2, potency: 5 }, xpReward: 205, goldReward: [66, 118], dropTable: [{ itemId: 'dune_chitin', chance: 0.78, min: 2, max: 3 }, { itemId: 'sun_salt', chance: 0.5, min: 1, max: 2 }] },
  ember_acolyte: { id: 'ember_acolyte', name: { [EN]: 'Ember Acolyte', [RU]: 'Аколит тлеющего пламени' }, role: 'alchemist', level: 8, hp: 92, maxHp: 92, maxEnergy: 116, damage: [10, 17], damageType: 'fire', statusInflict: { type: 'bleeding', chance: 0.3, duration: 2, potency: 5 }, xpReward: 152, goldReward: [38, 84], dropTable: [{ itemId: 'phoenix_ash', chance: 0.55, min: 1, max: 2 }, { itemId: 'relic_ink', chance: 0.45, min: 1, max: 2 }] },
  brass_colossus: { id: 'brass_colossus', name: { [EN]: 'Brass Colossus', [RU]: 'Латунный колосс' }, role: 'boss', level: 12, hp: 290, maxHp: 290, maxEnergy: 160, damage: [17, 27], damageType: 'physical', resistances: { physical: 0.24, fire: 0.2, arcane: -0.1 }, phases: [{ thresholdHpPercent: 65, name: { [EN]: 'Overheated Core', [RU]: 'Перегретое ядро' }, damageMod: 1.2, defenseMod: 1.08 }, { thresholdHpPercent: 32, name: { [EN]: 'Solar Breach', [RU]: 'Солнечный прорыв' }, damageMod: 1.38, defenseMod: 1.04, statusImmunity: ['stunned'] }], xpReward: 520, goldReward: [180, 280], dropTable: [{ itemId: 'weapon_brass_halberd', chance: 0.2, min: 1, max: 1 }, { itemId: 'armor_catacomb_plate', chance: 0.2, min: 1, max: 1 }, { itemId: 'dawn_opal', chance: 0.95, min: 2, max: 4 }] },
};

export const EXPANSION_LOCATIONS: Record<string, Location> = {
  road_glassway: {
    id: 'road_glassway',
    name: { [EN]: 'Glassway', [RU]: 'Стеклянный тракт' },
    description: { [EN]: 'A bright caravan route across shattered mineral fields.', [RU]: 'Яркий караванный путь через расколотые минеральные поля.' },
    type: 'road',
    image: '/images/locations/road_glassway.svg',
    connectedLocations: ['road_concord', 'hub_dawnwatch', 'dunes_singed'],
    possibleEnemies: ['dune_reaver', 'glass_stalker', 'ember_acolyte'],
    possibleLoot: ['sun_salt', 'glass_bloom', 'gold'],
    merchantPriceMod: 1.13,
    allowedWeather: ['clear', 'storm'],
  },
  hub_dawnwatch: {
    id: 'hub_dawnwatch',
    name: { [EN]: 'Dawnwatch Forum', [RU]: 'Форум Рассветной Стражи' },
    description: { [EN]: 'A fortified civic market where guilds coordinate frontier contracts.', [RU]: 'Укреплённый городской рынок, где гильдии координируют пограничные контракты.' },
    type: 'hub',
    image: '/images/locations/hub_dawnwatch.svg',
    connectedLocations: ['road_glassway', 'observatory_shards'],
    npcs: ['npc_prefect_aurelia', 'npc_artificer_kael', 'npc_medic_selene', 'npc_pathfinder_orin'],
    craftingStations: ['forge', 'alchemy_table', 'runic_workbench'],
    merchantPriceMod: 1.08,
    allowedWeather: ['clear', 'rain', 'fog'],
  },
  dunes_singed: {
    id: 'dunes_singed',
    name: { [EN]: 'Singed Dunes', [RU]: 'Опалённые дюны' },
    description: { [EN]: 'Wind-cut dunes where caravans vanish in glittering storms.', [RU]: 'Выжженные ветром дюны, где караваны исчезают в сверкающих бурях.' },
    type: 'explore',
    image: '/images/locations/dunes_singed.svg',
    connectedLocations: ['road_glassway', 'quarry_sunscar', 'catacombs_veil'],
    possibleEnemies: ['dune_reaver', 'carrion_drake', 'glass_stalker'],
    possibleLoot: ['sun_salt', 'dune_chitin', 'glass_bloom'],
    merchantPriceMod: 1.19,
    allowedWeather: ['clear', 'storm'],
  },
  quarry_sunscar: {
    id: 'quarry_sunscar',
    name: { [EN]: 'Sunscar Quarry', [RU]: 'Карьер Солнечного Шрама' },
    description: { [EN]: 'Industrial pit where old automata mine blazing ore veins.', [RU]: 'Промышленный разрез, где старые автоматоны добывают раскалённые жилы.' },
    type: 'explore',
    image: '/images/locations/quarry_sunscar.svg',
    connectedLocations: ['dunes_singed', 'observatory_shards'],
    possibleEnemies: ['sun_automaton', 'ember_acolyte', 'oathbreaker_duelist'],
    possibleLoot: ['brass_core', 'sun_salt', 'iron_ore', 'silver_ore'],
    craftingStations: ['forge'],
    merchantPriceMod: 1.22,
    allowedWeather: ['clear', 'snow', 'storm'],
  },
  observatory_shards: {
    id: 'observatory_shards',
    name: { [EN]: 'Shard Observatory', [RU]: 'Осколочная обсерватория' },
    description: { [EN]: 'Ruined lens towers that refract moonlight into arcane hazards.', [RU]: 'Разрушенные башни линз, преломляющие лунный свет в тайные угрозы.' },
    type: 'explore',
    image: '/images/locations/observatory_shards.svg',
    connectedLocations: ['hub_dawnwatch', 'quarry_sunscar', 'catacombs_veil'],
    possibleEnemies: ['glass_stalker', 'oathbreaker_duelist', 'crypt_wailer'],
    possibleLoot: ['dawn_opal', 'relic_ink', 'crystal_shard'],
    craftingStations: ['runic_workbench'],
    merchantPriceMod: 1.21,
    allowedWeather: ['clear', 'fog', 'rain'],
  },
  catacombs_veil: {
    id: 'catacombs_veil',
    name: { [EN]: 'Veil Catacombs', [RU]: 'Катакомбы Завесы' },
    description: { [EN]: 'Deep vaults beneath the dunes where forgotten oaths still echo.', [RU]: 'Глубокие своды под дюнами, где до сих пор звучат забытые клятвы.' },
    type: 'explore',
    image: '/images/locations/catacombs_veil.svg',
    connectedLocations: ['dunes_singed', 'observatory_shards'],
    possibleEnemies: ['crypt_wailer', 'oathbreaker_duelist', 'brass_colossus'],
    possibleLoot: ['veil_thread', 'relic_ink', 'phoenix_ash', 'dawn_opal'],
    craftingStations: ['runic_workbench', 'forge'],
    merchantPriceMod: 1.27,
    allowedWeather: ['fog', 'clear'],
  },
};

export const EXPANSION_MERCHANTS: Record<string, Merchant> = {
  merchant_prefect_aurelia: {
    id: 'merchant_prefect_aurelia',
    name: { [EN]: 'Forum Contracts', [RU]: 'Контракты Форума' },
    locationId: 'hub_dawnwatch',
    inventory: [
      { itemId: 'scroll_sun_lance', price: 235 },
      { itemId: 'scroll_veilstep', price: 210 },
      { itemId: 'dawn_opal', price: 78 },
      { itemId: 'gold', price: 2 },
    ],
  },
  merchant_artificer_kael: {
    id: 'merchant_artificer_kael',
    name: { [EN]: 'Kael Forge Arsenal', [RU]: 'Арсенал Келя' },
    locationId: 'hub_dawnwatch',
    inventory: [
      { itemId: 'weapon_sun_lance', price: 740 },
      { itemId: 'weapon_brass_halberd', price: 780 },
      { itemId: 'weapon_glass_dagger', price: 410 },
      { itemId: 'armor_glass_mail', price: 720 },
      { itemId: 'armor_catacomb_plate', price: 790 },
      { itemId: 'brass_core', price: 94 },
      { itemId: 'sun_salt', price: 32 },
    ],
  },
  merchant_medic_selene: {
    id: 'merchant_medic_selene',
    name: { [EN]: 'Selene Apothecary', [RU]: 'Аптека Селены' },
    locationId: 'hub_dawnwatch',
    inventory: [
      { itemId: 'potion_sunfire', price: 118 },
      { itemId: 'potion_veilstep', price: 116 },
      { itemId: 'potion_guard_tonic', price: 124 },
      { itemId: 'bomb_glass_shard', price: 128 },
      { itemId: 'bomb_dusk_smoke', price: 156 },
      { itemId: 'sun_salt', price: 30 },
      { itemId: 'veil_thread', price: 42 },
    ],
  },
  merchant_pathfinder_orin: {
    id: 'merchant_pathfinder_orin',
    name: { [EN]: 'Orin Trail Exchange', [RU]: 'Путевой обмен Орина' },
    locationId: 'hub_dawnwatch',
    inventory: [
      { itemId: 'dune_chitin', price: 32 },
      { itemId: 'glass_bloom', price: 44 },
      { itemId: 'relic_ink', price: 49 },
      { itemId: 'veil_thread', price: 41 },
      { itemId: 'weapon_veil_bow', price: 760 },
      { itemId: 'armor_dune_cloak', price: 420 },
      { itemId: 'armor_dawn_robe', price: 490 },
    ],
  },
};

export const EXPANSION_NPCS: Record<string, NPC> = {
  npc_prefect_aurelia: {
    id: 'npc_prefect_aurelia',
    name: { [EN]: 'Prefect Aurelia', [RU]: 'Префект Аурелия' },
    locationId: 'hub_dawnwatch',
    defaultNode: 'start',
    dialogueTree: {
      start: {
        id: 'start',
        text: { [EN]: 'Dawnwatch stands because contracts are honored and routes stay open.', [RU]: 'Рассветная Стража стоит, пока договоры соблюдаются, а пути остаются открытыми.' },
        options: [
          { text: { [EN]: 'I can secure the convoy routes.', [RU]: 'Я могу обезопасить караванные пути.' }, nextNodeId: 'route', action: 'give_quest', actionPayload: 'quest_dawn_convoy' },
          { text: { [EN]: 'Need opals for city reserves?', [RU]: 'Нужны опалы для городского резерва?' }, nextNodeId: 'opals', action: 'give_quest', actionPayload: 'quest_opal_ledger' },
          { text: { [EN]: 'Open forum contracts.', [RU]: 'Открыть контракты форума.' }, nextNodeId: 'start', action: 'open_merchant', actionPayload: 'merchant_prefect_aurelia' },
          { text: { [EN]: 'I will return.', [RU]: 'Я вернусь.' }, nextNodeId: null },
        ],
      },
      route: { id: 'route', text: { [EN]: 'Reavers strike at dusk. Break their pressure and caravans move again.', [RU]: 'Мародёры бьют в сумерках. Сломай их давление, и караваны снова пойдут.' }, options: [{ text: { [EN]: 'Understood.', [RU]: 'Понял.' }, nextNodeId: null }] },
      opals: { id: 'opals', text: { [EN]: 'Bring opals from observatory ruins. We need stable lenses for signal towers.', [RU]: 'Принеси опалы из руин обсерватории. Нам нужны стабильные линзы для сигнальных башен.' }, options: [{ text: { [EN]: 'On my way.', [RU]: 'Уже иду.' }, nextNodeId: null }] },
    },
  },
  npc_artificer_kael: {
    id: 'npc_artificer_kael',
    name: { [EN]: 'Artificer Kael', [RU]: 'Артификер Кель' },
    locationId: 'hub_dawnwatch',
    defaultNode: 'start',
    dialogueTree: {
      start: {
        id: 'start',
        text: { [EN]: 'Metal, heat and sequence. Miss sequence and your weapon dies in your hands.', [RU]: 'Металл, жар и порядок. Нарушишь порядок - оружие умрёт в твоих руках.' },
        options: [
          { text: { [EN]: 'I can gather brass cores.', [RU]: 'Я соберу латунные ядра.' }, nextNodeId: 'cores', action: 'give_quest', actionPayload: 'quest_quarry_cores' },
          { text: { [EN]: 'Any major machine threat?', [RU]: 'Есть крупная машинная угроза?' }, nextNodeId: 'colossus', action: 'give_quest', actionPayload: 'quest_colossus_fall' },
          { text: { [EN]: 'Open forge arsenal.', [RU]: 'Открыть кузнечный арсенал.' }, nextNodeId: 'start', action: 'open_merchant', actionPayload: 'merchant_artificer_kael' },
          { text: { [EN]: 'Later.', [RU]: 'Позже.' }, nextNodeId: null },
        ],
      },
      cores: { id: 'cores', text: { [EN]: 'Three intact cores from the quarry. No cracked casings.', [RU]: 'Три целых сердечника из карьера. Без треснувших корпусов.' }, options: [{ text: { [EN]: 'I will deliver them.', [RU]: 'Доставлю.' }, nextNodeId: null }] },
      colossus: { id: 'colossus', text: { [EN]: 'A brass colossus woke beneath the catacombs. Bring it down before it reaches the forum.', [RU]: 'Под катакомбами пробудился латунный колосс. Сломай его до того, как он доберётся до форума.' }, options: [{ text: { [EN]: 'I take the contract.', [RU]: 'Контракт принят.' }, nextNodeId: null }] },
    },
  },
  npc_medic_selene: {
    id: 'npc_medic_selene',
    name: { [EN]: 'Medic Selene', [RU]: 'Медик Селена' },
    locationId: 'hub_dawnwatch',
    defaultNode: 'start',
    dialogueTree: {
      start: {
        id: 'start',
        text: { [EN]: 'Field medicine keeps soldiers alive long enough to become veterans.', [RU]: 'Полевая медицина держит бойцов в строю, пока они не станут ветеранами.' },
        options: [
          { text: { [EN]: 'Need medicinal fibers?', [RU]: 'Нужны медицинские волокна?' }, nextNodeId: 'fibers', action: 'give_quest', actionPayload: 'quest_veil_threads' },
          { text: { [EN]: 'Need drake reagents?', [RU]: 'Нужны реагенты дрейка?' }, nextNodeId: 'drake', action: 'give_quest', actionPayload: 'quest_carrion_drake' },
          { text: { [EN]: 'Open apothecary stock.', [RU]: 'Открыть аптечные запасы.' }, nextNodeId: 'start', action: 'open_merchant', actionPayload: 'merchant_medic_selene' },
          { text: { [EN]: 'Stay safe.', [RU]: 'Берегите себя.' }, nextNodeId: null },
        ],
      },
      fibers: { id: 'fibers', text: { [EN]: 'Bring six veil threads. We stitch pressure wraps from them.', [RU]: 'Принеси шесть нитей завесы. Из них шьются компрессионные повязки.' }, options: [{ text: { [EN]: 'I will bring them.', [RU]: 'Принесу.' }, nextNodeId: null }] },
      drake: { id: 'drake', text: { [EN]: 'Carrion drakes poison routes. Eliminate them and harvest stable chitin.', [RU]: 'Падальные дрейки травят маршруты. Устрани их и добудь стабильный хитин.' }, options: [{ text: { [EN]: 'Consider it done.', [RU]: 'Сделаю.' }, nextNodeId: null }] },
    },
  },
  npc_pathfinder_orin: {
    id: 'npc_pathfinder_orin',
    name: { [EN]: 'Pathfinder Orin', [RU]: 'Проводник Орин' },
    locationId: 'hub_dawnwatch',
    defaultNode: 'start',
    dialogueTree: {
      start: {
        id: 'start',
        text: { [EN]: 'Routes change every week. Survive the map, and the map starts helping you.', [RU]: 'Маршруты меняются каждую неделю. Выживешь на карте - и карта начнёт помогать тебе.' },
        options: [
          { text: { [EN]: 'I can clear the glassway.', [RU]: 'Я могу зачистить стеклянный тракт.' }, nextNodeId: 'glassway', action: 'give_quest', actionPayload: 'quest_glassway_stalkers' },
          { text: { [EN]: 'Need map marks from catacombs?', [RU]: 'Нужны метки маршрута из катакомб?' }, nextNodeId: 'catacombs', action: 'give_quest', actionPayload: 'quest_catacomb_marks' },
          { text: { [EN]: 'Open trail exchange.', [RU]: 'Открыть путевой обмен.' }, nextNodeId: 'start', action: 'open_merchant', actionPayload: 'merchant_pathfinder_orin' },
          { text: { [EN]: 'We talk later.', [RU]: 'Поговорим позже.' }, nextNodeId: null },
        ],
      },
      glassway: { id: 'glassway', text: { [EN]: 'Remove four glass stalkers near the route markers.', [RU]: 'Устрани четырёх стеклянных охотников у маршрутных меток.' }, options: [{ text: { [EN]: 'Accepted.', [RU]: 'Принято.' }, nextNodeId: null }] },
      catacombs: { id: 'catacombs', text: { [EN]: 'Bring relic ink and opal marks from the catacombs. We need fresh maps.', [RU]: 'Принеси реликтовые чернила и опаловые метки из катакомб. Нужны свежие карты.' }, options: [{ text: { [EN]: 'I will scout it.', [RU]: 'Разведаю.' }, nextNodeId: null }] },
    },
  },
};

export const EXPANSION_QUESTS: Record<string, Quest> = {
  quest_dawn_convoy: {
    id: 'quest_dawn_convoy',
    giverNpcId: 'npc_prefect_aurelia',
    turnInNpcId: 'npc_prefect_aurelia',
    name: { [EN]: 'Convoy Stabilization', [RU]: 'Стабилизация конвоя' },
    description: { [EN]: 'Defeat 4 dune reavers threatening convoy lanes.', [RU]: 'Победите 4 дюнных мародёров, угрожающих караванным путям.' },
    locationId: 'dunes_singed',
    goals: [{ type: 'kill', targetId: 'dune_reaver', targetCount: 4, currentCount: 0 }],
    rewards: { xp: 280, gold: 230, items: [{ itemId: 'armor_dune_cloak', quantity: 1 }] },
    isTurnInReady: false,
    isCompleted: false,
  },
  quest_opal_ledger: {
    id: 'quest_opal_ledger',
    giverNpcId: 'npc_prefect_aurelia',
    turnInNpcId: 'npc_prefect_aurelia',
    name: { [EN]: 'Opal Ledger', [RU]: 'Опаловый реестр' },
    description: { [EN]: 'Collect 5 dawn opals for signal-lens contracts.', [RU]: 'Соберите 5 рассветных опалов для контрактов сигнальных линз.' },
    locationId: 'observatory_shards',
    goals: [{ type: 'collect', targetId: 'dawn_opal', targetCount: 5, currentCount: 0 }],
    rewards: { xp: 255, gold: 210, items: [{ itemId: 'scroll_sun_lance', quantity: 1 }] },
    isTurnInReady: false,
    isCompleted: false,
  },
  quest_quarry_cores: {
    id: 'quest_quarry_cores',
    giverNpcId: 'npc_artificer_kael',
    turnInNpcId: 'npc_artificer_kael',
    name: { [EN]: 'Core Recovery', [RU]: 'Извлечение сердечников' },
    description: { [EN]: 'Recover 3 brass cores from Sunscar Quarry.', [RU]: 'Добудьте 3 латунных сердечника в Карьере Солнечного Шрама.' },
    locationId: 'quarry_sunscar',
    goals: [{ type: 'collect', targetId: 'brass_core', targetCount: 3, currentCount: 0 }],
    rewards: { xp: 290, gold: 240, items: [{ itemId: 'weapon_glass_dagger', quantity: 1 }] },
    isTurnInReady: false,
    isCompleted: false,
  },
  quest_colossus_fall: {
    id: 'quest_colossus_fall',
    giverNpcId: 'npc_artificer_kael',
    turnInNpcId: 'npc_artificer_kael',
    name: { [EN]: 'Fall of the Colossus', [RU]: 'Падение колосса' },
    description: { [EN]: 'Defeat the Brass Colossus beneath the Veil Catacombs.', [RU]: 'Победите Латунного колосса под Катакомбами Завесы.' },
    locationId: 'catacombs_veil',
    goals: [{ type: 'kill', targetId: 'brass_colossus', targetCount: 1, currentCount: 0 }],
    rewards: { xp: 620, gold: 430, items: [{ itemId: 'weapon_brass_halberd', quantity: 1 }, { itemId: 'armor_catacomb_plate', quantity: 1 }] },
    isTurnInReady: false,
    isCompleted: false,
  },
  quest_veil_threads: {
    id: 'quest_veil_threads',
    giverNpcId: 'npc_medic_selene',
    turnInNpcId: 'npc_medic_selene',
    name: { [EN]: 'Sutures of the Veil', [RU]: 'Швы завесы' },
    description: { [EN]: 'Collect 6 veil threads for field medicine kits.', [RU]: 'Соберите 6 нитей завесы для полевых медицинских наборов.' },
    locationId: 'catacombs_veil',
    goals: [{ type: 'collect', targetId: 'veil_thread', targetCount: 6, currentCount: 0 }],
    rewards: { xp: 250, gold: 205, items: [{ itemId: 'scroll_veilstep', quantity: 1 }, { itemId: 'potion_guard_tonic', quantity: 2 }] },
    isTurnInReady: false,
    isCompleted: false,
  },
  quest_carrion_drake: {
    id: 'quest_carrion_drake',
    giverNpcId: 'npc_medic_selene',
    turnInNpcId: 'npc_medic_selene',
    name: { [EN]: 'Carrion Suppression', [RU]: 'Подавление падальщиков' },
    description: { [EN]: 'Defeat 2 carrion drakes and secure route safety.', [RU]: 'Победите 2 падальных дрейков и обезопасьте маршруты.' },
    locationId: 'dunes_singed',
    goals: [{ type: 'kill', targetId: 'carrion_drake', targetCount: 2, currentCount: 0 }],
    rewards: { xp: 315, gold: 260, items: [{ itemId: 'potion_sunfire', quantity: 2 }, { itemId: 'bomb_dusk_smoke', quantity: 1 }] },
    isTurnInReady: false,
    isCompleted: false,
  },
  quest_glassway_stalkers: {
    id: 'quest_glassway_stalkers',
    giverNpcId: 'npc_pathfinder_orin',
    turnInNpcId: 'npc_pathfinder_orin',
    name: { [EN]: 'Glassway Sweep', [RU]: 'Зачистка стеклянного тракта' },
    description: { [EN]: 'Eliminate 4 glass stalkers along Glassway.', [RU]: 'Уничтожьте 4 стеклянных охотников на Стеклянном тракте.' },
    locationId: 'road_glassway',
    goals: [{ type: 'kill', targetId: 'glass_stalker', targetCount: 4, currentCount: 0 }],
    rewards: { xp: 275, gold: 215, items: [{ itemId: 'weapon_veil_bow', quantity: 1 }] },
    isTurnInReady: false,
    isCompleted: false,
  },
  quest_catacomb_marks: {
    id: 'quest_catacomb_marks',
    giverNpcId: 'npc_pathfinder_orin',
    turnInNpcId: 'npc_pathfinder_orin',
    name: { [EN]: 'Catacomb Cartography', [RU]: 'Картография катакомб' },
    description: { [EN]: 'Collect 4 relic ink and 3 dawn opals to update route maps.', [RU]: 'Соберите 4 реликтовые чернила и 3 рассветных опала для обновления маршрутных карт.' },
    locationId: 'catacombs_veil',
    goals: [
      { type: 'collect', targetId: 'relic_ink', targetCount: 4, currentCount: 0 },
      { type: 'collect', targetId: 'dawn_opal', targetCount: 3, currentCount: 0 },
    ],
    rewards: { xp: 300, gold: 240, items: [{ itemId: 'armor_dawn_robe', quantity: 1 }, { itemId: 'bomb_glass_shard', quantity: 1 }] },
    isTurnInReady: false,
    isCompleted: false,
  },
};

export const EXPANSION_CONNECTIONS: Array<[string, string]> = [
  ['road_concord', 'road_glassway'],
  ['road_glassway', 'hub_dawnwatch'],
  ['road_glassway', 'dunes_singed'],
  ['hub_dawnwatch', 'observatory_shards'],
  ['dunes_singed', 'quarry_sunscar'],
  ['dunes_singed', 'catacombs_veil'],
  ['quarry_sunscar', 'observatory_shards'],
  ['observatory_shards', 'catacombs_veil'],
];
